name: Update Repo
on:
  push:
    paths:
      - 'debs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Packages
      run: |
        dpkg-scanpackages debs /dev/null > Packages
        gzip -c9 Packages > Packages.gz
        bzip2 -c9 Packages > Packages.bz2
        xz -c9 Packages > Packages.xz
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Update Packages" || echo "No changes to commit"
        git push
