name: Update Repo
on:
  push:
    paths:
      - 'debs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up dpkg
        run: sudo apt-get install -y dpkg-dev
      - name: Generate Packages
        run: |
          dpkg-scanpackages debs /dev/null > Packages
          gzip -c9 Packages > Packages.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: repo-files
          path: |
            Packages
            Packages.gz
